# Generated by Django 4.2.6 on 2023-10-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canBeRented', models.BooleanField()),
                ('transportType', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Scooter', 'Scooter')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('minutePrice', models.FloatField()),
                ('dayPrice', models.FloatField()),
            ],
        ),
    ]
