# Generated by Django 4.2.6 on 2023-10-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportController', '0002_transport_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='identifier',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
