# Generated by Django 4.2.6 on 2023-10-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportController', '0003_transport_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='dayPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='minutePrice',
            field=models.FloatField(null=True),
        ),
    ]
