# Generated by Django 4.2.6 on 2023-10-21 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TransportController', '0004_alter_transport_dayprice_alter_transport_minuteprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to=settings.AUTH_USER_MODEL),
        ),
    ]
