# Generated by Django 4.2.6 on 2023-10-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentController', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='rentType',
            new_name='priceType',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='ended_at',
            new_name='timeEnd',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='created_at',
            new_name='timeStart',
        ),
        migrations.AddField(
            model_name='rent',
            name='finalPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='priceOfUnit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
