# Generated by Django 4.2.6 on 2023-10-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentController', '0002_rename_renttype_rent_pricetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='finalPrice',
            field=models.FloatField(default=0, null=True),
        ),
    ]
